from numpy import ndarray, _Scalar, bool_
from typing import Generic

class MaskedArray(ndarray[_Scalar]): ...

def array(data: ndarray[_Scalar], mask: ndarray[bool_] = ...) -> MaskedArray[_Scalar]: ...
def dot(a: MaskedArray[_Scalar], b: MaskedArray[_Scalar]) -> MaskedArray[_Scalar]: ...
def masked_array(data: ndarray[_Scalar], mask: ndarray[_Scalar]) -> MaskedArray[_Scalar]: ...
def median(data: MaskedArray[_Scalar]) -> _Scalar: ...
