from ._core import _ShapeType, ndarray

def permutation(size: int) -> ndarray[int]: ...
def seed(s: int) -> None: ...
def shuffle(x: ndarray) -> None: ...
def uniform(size: _ShapeType) -> ndarray: ...

class RandomState:
    def __init__(self, seed: int = ...): ...
    def permutation(self, size: int) -> ndarray[int]: ...
    def shuffle(self, x: ndarray) -> None: ...
    def uniform(self, size: _ShapeType) -> ndarray: ...
