from ._core import DataFrame, Index, Series

def assert_frame_equal(left: DataFrame, right: DataFrame) -> None: ...
def assert_index_equal(left: Index, right: Index) -> None: ...
def assert_series_equal(left: Series, right: Series) -> None: ...
