from typing import overload, Optional, Union, List, Dict, Iterator

from pandas.core.frame import DataFrame
from pandas.core.series import Series
from ..frame import _FunctionLike

_str = str  # needed because Series has a property called "str"...

class GroupBy: ...

class DataFrameGroupBy(GroupBy):
    @overload
    def __getitem__(self, item: _str) -> SeriesGroupBy: ...
    @overload
    def __getitem__(self, item: List[_str]) -> DataFrameGroupBy: ...
    def __getattr__(self, name: _str) -> SeriesGroupBy: ...
    def __iter__(self) -> Iterator: ...
    def aggregate(
        self,
        func: Union[_FunctionLike, List[_FunctionLike], Dict[_str, _FunctionLike]],
    ) -> DataFrame: ...
    agg = aggregate

class SeriesGroupBy(GroupBy):
    def __getitem__(self, item: _str) -> Series: ...
    def max(self) -> Series: ...
    def mean(self) -> Series: ...
    def median(self) -> Series: ...
    def min(self) -> Series: ...
    def std(self, ddof: int = ...) -> Series: ...
